export const AUTH_SEARCH_ACCOUNT_REQUEST = "AUTH_SEARCH_ACCOUNT_REQUEST";
export const AUTH_SEARCH_ACCOUNT_SUCCESS = "AUTH_SEARCH_ACCOUNT_SUCCESS";
export const AUTH_SEARCH_ACCOUNT_FAIL = "AUTH_SEARCH_ACCOUNT_FAIL";
export const AUTH_SEARCH_ACCOUNT_RESET = "AUTH_SEARCH_ACCOUNT_RESET";

export const AUTH_RESET_ACCOUNT_REQUEST = "AUTH_RESET_ACCOUNT_REQUEST";
export const AUTH_RESET_ACCOUNT_SUCCESS = "AUTH_RESET_ACCOUNT_SUCCESS";
export const AUTH_RESET_ACCOUNT_FAIL = "AUTH_RESET_ACCOUNT_FAIL";

export const GET_AUTH_ACCOUNT_REQUEST = "GET_AUTH_ACCOUNT_REQUEST";
export const GET_AUTH_ACCOUNT_SUCCESS = "GET_AUTH_ACCOUNT_SUCCESS";
export const GET_AUTH_ACCOUNT_FAIL = "GET_AUTH_ACCOUNT_FAIL";
