export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_START = "CREATE_POST_START";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_START = "GET_POST_START";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_START = "UPDATE_POST_START";
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_START = "DELETE_POST_START";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const USER_POST_REQUEST = "USER_POST_REQUEST";
export const USER_POST_SUCCESS = "USER_POST_SUCCESS";
export const USER_POST_START = "USER_POST_START";
export const USER_POST_FAIL = "USER_POST_FAIL";

export const GET_ALL_POST_REQUEST = "GET_ALL_POST_REQUEST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_START = "GET_ALL_POST_START";
export const GET_ALL_POST_FAIL = "GET_ALL_POST_FAIL";

